#!/usr/bin/env bun
/**
 * Builds self-contained single-file binaries for all platforms.
 *
 * Steps:
 *  1. Build the Vite web client
 *  2. Encode all dist files into server/src/_embedded.ts
 *  3. bun build --compile for each target platform
 *  4. Restore server/src/_embedded.ts to its stub state
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';

const ROOT = join(import.meta.dir, '..');
const DIST_DIR = join(ROOT, 'web-client', 'dist');
const EMBEDDED_FILE = join(ROOT, 'server', 'src', '_embedded.ts');
const OUT_DIR = join(ROOT, 'dist', 'binaries');

const MIME_MAP: Record<string, string> = {
  html: 'text/html; charset=utf-8',
  js:   'application/javascript',
  mjs:  'application/javascript',
  css:  'text/css',
  json: 'application/json',
  png:  'image/png',
  jpg:  'image/jpeg',
  jpeg: 'image/jpeg',
  gif:  'image/gif',
  svg:  'image/svg+xml',
  ico:  'image/x-icon',
  woff: 'font/woff',
  woff2:'font/woff2',
  ttf:  'font/ttf',
  webp: 'image/webp',
  txt:  'text/plain',
};

const STUB = `// Static files are embedded here during binary builds (see scripts/build-binary.ts).
// In Docker / dev this file is not used — the server falls back to the file system.
export const files: Map<string, { b64: string; mime: string }> | null = null;
`;

function mime(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  return MIME_MAP[ext] ?? 'application/octet-stream';
}

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) results.push(...walk(full));
    else results.push(full);
  }
  return results;
}

const TARGETS = [
  { name: 'linux-x64',   target: 'bun-linux-x64'   },
  { name: 'linux-arm64', target: 'bun-linux-arm64'  },
  { name: 'macos-x64',   target: 'bun-darwin-x64'   },
  { name: 'macos-arm64', target: 'bun-darwin-arm64'  },
  { name: 'windows-x64', target: 'bun-windows-x64', ext: '.exe' },
];

try {
  // 1. Build web client
  console.log('\n[1/4] Building web client...');
  execSync('npm run build', { cwd: join(ROOT, 'web-client'), stdio: 'inherit' });

  // 2. Generate embedded static file map
  console.log('\n[2/4] Embedding static files...');
  const files = walk(DIST_DIR);
  const entries = files.map(f => {
    const urlPath = '/' + relative(DIST_DIR, f).replace(/\\/g, '/');
    const b64 = readFileSync(f).toString('base64');
    return `  ['${urlPath}', { b64: '${b64}', mime: '${mime(f)}' }]`;
  });

  writeFileSync(EMBEDDED_FILE, `// AUTO-GENERATED by scripts/build-binary.ts — do not edit
export const files = new Map<string, { b64: string; mime: string }>([
${entries.join(',\n')}
]);
`);
  console.log(`  Embedded ${files.length} files`);

  // 3. Compile binaries for each platform
  console.log('\n[3/4] Compiling binaries...');
  execSync(`mkdir -p ${OUT_DIR}`);

  for (const { name, target, ext = '' } of TARGETS) {
    const outFile = join(OUT_DIR, `sonos-controller-${name}${ext}`);
    console.log(`  → ${name}`);
    execSync(
      `bun build --compile --target=${target} src/index.ts --outfile=${outFile}`,
      { cwd: join(ROOT, 'server'), stdio: 'inherit' }
    );
  }

  console.log('\n[4/4] Restoring stub...');
  writeFileSync(EMBEDDED_FILE, STUB);

  console.log('\n✓ Binaries written to dist/binaries/');
  for (const { name, ext = '' } of TARGETS) {
    console.log(`  dist/binaries/sonos-controller-${name}${ext}`);
  }

} catch (err) {
  // Always restore stub even on failure
  writeFileSync(EMBEDDED_FILE, STUB);
  console.error('\nBuild failed:', err);
  process.exit(1);
}
